"""Auditable Android-only source repair. Distributable source is ordinary Java, not transport chunks."""
from pathlib import Path
import sys, hashlib
root=Path(sys.argv[1]); j=root/'app/src/main/java/uk/co/sumerostudio/nexuai3dforge'; p=j/'MainActivity.java'
s=p.read_text()
def change(signature,code):
    global s
    start=s.index(signature); brace=s.index('{',start); depth=0; quote=None; escape=False
    for k in range(brace,len(s)):
        c=s[k]
        if quote:
            if escape: escape=False
            elif c=='\\': escape=True
            elif c==quote: quote=None
        elif c in ('"',"'"): quote=c
        elif c=='{': depth+=1
        elif c=='}':
            depth-=1
            if depth==0:s=s[:start]+code.strip('\n')+s[k+1:];return
    raise ValueError('Method boundary not found: '+signature)
s=s.replace('new JSONObject()','new JsonObject()').replace('JSONObject params=new JsonObject()','JsonObject params=new JsonObject()').replace('JSONObject p=new JsonObject()','JsonObject p=new JsonObject()')
s=s.replace('private Spinner profile,mode,materialPreset,lod;','''private Spinner profile,mode,materialPreset,lod,materialSlot;
    private View createPage;
    private volatile int transferVersion;
    private int selectedLod,pollVersion;
    private volatile boolean writeBusy;
    private String pendingDirectory="",lodDirectory="",referenceUri="",localUri="";
    private byte[] pendingModel,pendingCollision;
    private final List<String> presetIds=new ArrayList<>(),materialNames=new ArrayList<>();
    private final java.util.EnumMap<Screen,Button> navigation=new java.util.EnumMap<>(Screen.class);''')
change('    @Override protected void onCreate(',r'''
    @Override protected void onCreate(Bundle saved) {
        super.onCreate(saved);configureWindow();client=new ForgeCompanionClient(new SecurePairingStore(this));
        restoreUi(saved);buildChrome();showScreen(currentScreen);registerPredictiveBack();
        ui.post(()->processIntent(getIntent()));
        runAsync(()->{client.restore();return client.isPaired();},paired->{renderPairState();if(paired){refreshAssets();refreshJobs();loadPresets();resumePersistedJob();}},"Restore pairing");
        restoreDocuments();
    }''')
change('    @Override protected void onStart(',r'''
    @Override protected void onStart(){super.onStart();started=true;if(viewer!=null&&currentScreen==Screen.CREATE)viewer.onResume();renderPairState();if(client.isPaired()){refreshAssets();refreshJobs();resumePersistedJob();}displayPending();}
''')
change('    @Override protected void onStop(',r'''
    @Override protected void onStop(){started=false;stopPolling();persistUi();if(viewer!=null)viewer.onPause();super.onStop();}
''')
change('    @Override protected void onDestroy(',r'''
    @Override protected void onDestroy(){stopPolling();transferVersion++;pendingModel=null;pendingCollision=null;client.cancelPending();io.shutdownNow();ui.removeCallbacksAndMessages(null);if(viewer!=null){ViewGroup parent=(ViewGroup)viewer.getParent();if(parent!=null)parent.removeView(viewer);viewer.stopLoading();viewer.destroy();viewer=null;}super.onDestroy();}
''')
change('    @Override protected void onSaveInstanceState(',r'''
    @Override protected void onSaveInstanceState(Bundle out){persistUi();out.putString("screen",currentScreen.name());out.putString("lastJob",lastJobId);super.onSaveInstanceState(out);}
''')
change('    private void configureWindow(',r'''
    private void configureWindow(){Window w=getWindow();w.setDecorFitsSystemWindows(false);WindowInsetsController c=w.getInsetsController();if(c!=null)c.setSystemBarsAppearance(0,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);}
''')
s=s.replace('root.setFitsSystemWindows(true);','''root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars()|android.view.WindowInsets.Type.displayCutout());android.graphics.Insets ime=insets.getInsets(android.view.WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,ime.bottom));return insets;});''')
s=s.replace('LinearLayout header=row();','LinearLayout header=column();').replace('header.addView(title,new LinearLayout.LayoutParams(0,dp(48),1))','header.addView(title,new LinearLayout.LayoutParams(-1,-2))').replace('topStatus.setGravity(Gravity.CENTER_VERTICAL|Gravity.END)','topStatus.setGravity(Gravity.CENTER_VERTICAL)').replace('header.addView(topStatus,new LinearLayout.LayoutParams(dp(190),dp(48)))','header.addView(topStatus,new LinearLayout.LayoutParams(-1,-2))').replace('root.addView(header,new LinearLayout.LayoutParams(-1,dp(68)))','root.addView(header,new LinearLayout.LayoutParams(-1,-2))')
s=s.replace('screenWidthDp>=840','screenWidthDp>=840&&getResources().getConfiguration().screenHeightDp>=500')
s=s.replace('b.setOnClickListener(v->showScreen(s));LinearLayout.LayoutParams','navigation.put(s,b);b.setOnClickListener(v->showScreen(s));LinearLayout.LayoutParams')
change('    private void showScreen(',r'''
    private void showScreen(Screen screen){currentScreen=screen;content.removeAllViews();View page;switch(screen){case LIBRARY:page=buildLibraryPage();break;case QUEUE:page=buildQueuePage();break;case PAIR:page=buildPairPage();break;default:if(createPage==null)createPage=buildCreatePage();page=createPage;}ViewGroup parent=(ViewGroup)page.getParent();if(parent!=null)parent.removeView(page);content.addView(page,new FrameLayout.LayoutParams(-1,-1));for(java.util.Map.Entry<Screen,Button> e:navigation.entrySet()){e.getValue().setSelected(e.getKey()==screen);e.getValue().setTextColor(e.getKey()==screen?ACCENT:TEXT);}if(viewer!=null){if(screen==Screen.CREATE&&started)viewer.onResume();else viewer.onPause();}if(screen==Screen.LIBRARY)refreshAssets();if(screen==Screen.QUEUE)refreshJobs();if(screen==Screen.PAIR)renderPairState();if(screen==Screen.CREATE){displayPending();if(selectedAsset!=null&&!selectedAsset.optString("directory").equals(lodDirectory))ui.post(()->loadSelectedAsset(selectedLod,true));}persistUi();}
''')
s=s.replace('else{main.addView(scroll,new LinearLayout.LayoutParams(-1,0,.58f));main.addView(viewPane,new LinearLayout.LayoutParams(-1,0,.42f));}','else{scroll.removeView(controls);ScrollView phone=new ScrollView(this);LinearLayout flow=column();flow.addView(viewPane,new LinearLayout.LayoutParams(-1,dp(390)));flow.addView(controls,new LinearLayout.LayoutParams(-1,-2));phone.addView(flow);main.addView(phone,new LinearLayout.LayoutParams(-1,-1));}')
s=s.replace('viewPane.addView(viewerBar);','HorizontalScrollView toolbar=new HorizontalScrollView(this);toolbar.setHorizontalScrollBarEnabled(false);toolbar.addView(viewerBar);viewPane.addView(toolbar,new LinearLayout.LayoutParams(-1,-2));')
s=s.replace('viewerBar.addView(b,new LinearLayout.LayoutParams(0,dp(48),1))','viewerBar.addView(b,new LinearLayout.LayoutParams(dp(86),dp(48)))')
s=s.replace('"Material","Solid","Wire","Collision","Frame"','"Colour","Solid","Wire","Collision","Frame","Left","Right","Zoom +","Zoom -"')
s=s.replace('position->{if(position>=0&&selectedAsset!=null)loadSelectedAsset(position,false);}','position->{if(position>=0&&position!=selectedLod&&selectedAsset!=null){selectedLod=position;loadSelectedAsset(position,true);}}')
s=s.replace('viewer=new WebView(this);configureViewer(viewer);viewPane.addView(viewer,new LinearLayout.LayoutParams(-1,0,1));','try{viewer=new WebView(this);configureViewer(viewer);viewPane.addView(viewer,new LinearLayout.LayoutParams(-1,0,1));}catch(RuntimeException e){viewer=null;viewPane.addView(caption("Android System WebView is unavailable. Update it to enable 3D inspection. Your asset files are safe."),new LinearLayout.LayoutParams(-1,0,1));}')
s=s.replace('button("Open local GLB")','button("Open GLB")').replace('button("Download GLB")','button("Save GLB")')
s=s.replace('controls.addView(createStatus);','createStatus.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);controls.addView(createStatus);')
s=s.replace('new String[]{"No preset","Aged Oak","Worn Iron","Rusted Iron","Dragon Scales","Wing Membrane","Horn & Claw","Coarse Fur","Feather","Chitin","Skin"}','new String[]{"Connect to load material presets"}')
s=s.replace('controls.addView(materialPreset,new LinearLayout.LayoutParams(-1,dp(54)));','controls.addView(materialPreset,new LinearLayout.LayoutParams(-1,dp(54)));materialSlot=spinner(new String[]{"First material slot"});materialSlot.setContentDescription("Material slot to change");controls.addView(materialSlot,new LinearLayout.LayoutParams(-1,dp(54)));if(client.isPaired())loadPresets();')
s=s.replace('controls.addView(referenceSummary);','''controls.addView(referenceSummary);Button send=button("Send reference to PC");send.setOnClickListener(v->{if(reference!=null&&ensurePaired())uploadReference(reference);else toast("Select a reference first.");});controls.addView(send,new LinearLayout.LayoutParams(-1,dp(54)));Button remove=button("Remove reference");remove.setOnClickListener(v->{reference=null;referenceUri="";referenceSummary.setText("No reference selected.");persistUi();});controls.addView(remove,new LinearLayout.LayoutParams(-1,dp(54)));''')
s=s.replace('controls.addView(briefSummary);','''controls.addView(briefSummary);Button catalogue=button("What can I create?");catalogue.setOnClickListener(v->showCatalogue());controls.addView(catalogue,new LinearLayout.LayoutParams(-1,dp(54)));''')
s=s.replace('scroll.addView(controls,new ScrollView.LayoutParams(-1,-2));','''Button good=button("Good result"),needs=button("Needs work");good.setOnClickListener(v->feedback("good"));needs.setOnClickListener(v->feedback("needs-work"));controls.addView(good,new LinearLayout.LayoutParams(-1,dp(54)));controls.addView(needs,new LinearLayout.LayoutParams(-1,dp(54)));controls.addView(caption("Static mesh colour / wireframe inspection. PBR textures, FBX and Blender source stay in the Windows asset folder. Generation uses the paired PC; neural image-to-3D is not included."));scroll.addView(controls,new ScrollView.LayoutParams(-1,-2));''')
s=s.replace('if(p.isEmpty()){toast("Describe an asset first.");return;}','if(p.isEmpty()||p.length()>2000){toast("Use 1–2,000 characters to describe the asset.");return;}')
s=s.replace('params.put("referenceEvidence",reference.evidenceJson())','params.put("referenceEvidence",new JSONArray().put(reference.evidenceJson()))')
change('    private void watchJob(',r'''
    private void watchJob(String id){if(id==null||id.isEmpty())return;lastJobId=id;persistUi();stopPolling();final int ticket=pollVersion;pollRunnable=new Runnable(){int failures;@Override public void run(){if(!started||ticket!=pollVersion||!client.isPaired()||isDestroyed())return;io.execute(()->{try{JSONObject r=client.rpc("job.get",new JsonObject().put("id",id));ui.post(()->{if(!started||ticket!=pollVersion||isDestroyed())return;JSONObject job=r.optJSONObject("job");if(job==null){setCreateStatus("Job not found. Inspect Queue before retrying.",0);return;}JobState state=new JobState(job);failures=0;setCreateStatus(state.label+(state.terminal?"":state.total>0?" · stage "+state.index+" of "+state.total:""),state.terminal?100:0);if(generationProgress!=null){generationProgress.setIndeterminate(!state.terminal&&state.index==0);generationProgress.setMax(state.total>0?state.total:100);generationProgress.setProgress(state.terminal?generationProgress.getMax():state.index);}if(state.terminal){lastJobId=null;stopPolling();persistUi();if(state.generated){pendingDirectory=state.directory;refreshAssets();}}else ui.postDelayed(this,1500);});}catch(Exception error){Diagnostics.record(MainActivity.this,"job polling",error);ui.post(()->{if(!started||ticket!=pollVersion||isDestroyed())return;setCreateStatus("Connection interrupted. Windows may still be generating. Rechecking…",0);ui.postDelayed(this,Math.min(30000L,1500L*(1L<<Math.min(4,++failures))));});}});}};if(started)ui.post(pollRunnable);}
''')
change('    private void stopPolling(',r'''    private void stopPolling(){pollVersion++;if(pollRunnable!=null)ui.removeCallbacks(pollRunnable);pollRunnable=null;}''')
s=s.replace('data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION)','data.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION')
s=s.replace('Uri uri=data.getData();try{','Uri uri=data.getData();if(!"content".equals(uri.getScheme())){showError("Unsupported file","Choose a file using Android Documents.");return;}try{')
s=s.replace('ev->{reference=ev;','ev->{reference=ev;referenceUri=uri.toString();persistUi();')
s=s.replace('if(client.isPaired())uploadReference(ev);','toast("Reference remains local. Generate sends palette evidence; Send reference transfers the image to your paired PC.");')
s=s.replace('bytes->{showGlbBytes(bytes,null);selectedAssetLabel.setText("Local GLB preview · not uploaded");}','bytes->{selectedAsset=null;localUri=uri.toString();persistUi();showGlbBytes(bytes,null);if(selectedAssetLabel!=null)selectedAssetLabel.setText("Local GLB preview · not uploaded");}')
s=s.replace('.put("view","reference")','.put("view","unclassified")')
change('    private void applyRefinement(',r'''
    private void applyRefinement(){if(!ensureAsset())return;String req=text(refineText);if(req.isEmpty()){toast("Describe the change first.");return;}previewChange("refine",new JsonObject().put("directory",selectedAsset.optString("directory")).put("request",req));}
''')
change('    private void applyMaterial(',r'''
    private void applyMaterial(){if(!ensureAsset())return;int i=materialPreset.getSelectedItemPosition();String preset=i>=0&&i<presetIds.size()?presetIds.get(i):"";JsonObject params=new JsonObject().put("directory",selectedAsset.optString("directory")).put("request",text(materialText)).put("preset",preset).put("resolution",512);int slot=materialSlot.getSelectedItemPosition();if(slot>=0&&slot<materialNames.size())params.put("materialName",materialNames.get(slot));previewChange("material",params);}
''')
s=s.replace('assets.add(x);}renderAssets();','assets.add(x);}renderAssets();if(!pendingDirectory.isEmpty()){String d=pendingDirectory;pendingDirectory="";selectAssetByDirectory(d);}')
s=s.replace('jobs.add(x);}renderJobs();','jobs.add(x);}renderJobs();String active=r.optString("activeJobId","");if(lastJobId==null&&!active.isEmpty()&&!active.equals("null")&&started)watchJob(active);')
s=s.replace('selectedAsset=a;showScreen(Screen.CREATE);ui.postDelayed(()->loadSelectedAsset(0,true),250);','selectedAsset=a;localUri="";selectedLod=0;showScreen(Screen.CREATE);loadSelectedAsset(0,true);')
s=s.replace('selectedAsset=a;downloadSelected(false);','selectedAsset=a;localUri="";downloadSelected(false);')
s=s.replace('selectedAsset=a;loadSelectedAsset(0,true);return;','selectedAsset=a;localUri="";if(currentScreen==Screen.CREATE)loadSelectedAsset(0,true);persistUi();return;')
s=s.replace('String status=j.optString("status","");if(', 'Button track=button("View progress");track.setOnClickListener(v->{showScreen(Screen.CREATE);watchJob(j.optString("id"));});card.addView(track,new LinearLayout.LayoutParams(-1,dp(52)));String status=j.optString("status","");if(')
change('    private void loadSelectedAsset(',r'''
    private void loadSelectedAsset(int level,boolean withCollision){if(selectedAsset==null||!client.isPaired()||createPage==null)return;String directory=selectedAsset.optString("directory");selectedAssetLabel.setText(selectedAsset.optString("displayName",selectedAsset.optString("assetName","Asset"))+" · "+selectedAsset.optInt("triangles",0)+" tris · "+selectedAsset.optString("qaLabel","QA pending"));int count=Math.max(0,Math.min(8,selectedAsset.optInt("lodCount",0)));selectedLod=Math.min(level,count);if(!directory.equals(lodDirectory)){lodDirectory=directory;List<String> names=new ArrayList<>();for(int i=0;i<=count;i++)names.add("LOD"+i);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,names);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);lod.setAdapter(adapter);updateMaterialSlots();}lod.setSelection(selectedLod);final int requested=selectedLod,ticket=++transferVersion;final boolean collision=withCollision&&selectedAsset.optBoolean("collisionCreated",false);runAsync(()->{byte[] model=decodeModel(client.rpc("asset.glb",new JsonObject().put("directory",directory).put("lod",requested).put("collision",false))),col=null;if(collision)try{col=decodeModel(client.rpc("asset.glb",new JsonObject().put("directory",directory).put("lod",0).put("collision",true)));}catch(Exception error){Diagnostics.record(this,"collision preview",error);}return new byte[][]{model,col};},data->{if(ticket==transferVersion){showGlbBytes(data[0],data[1]);persistUi();}},"3D preview unavailable");}
''')
change('    private void configureViewer(',r'''
    private void configureViewer(WebView w){viewerReady=false;WebView.setWebContentsDebuggingEnabled(false);WebSettings settings=w.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(false);settings.setGeolocationEnabled(false);settings.setAllowContentAccess(false);settings.setAllowFileAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setMediaPlaybackRequiresUserGesture(true);settings.setTextZoom(Math.max(100,Math.round(100*getResources().getConfiguration().fontScale)));android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(w,false);w.setBackgroundColor(BG);w.setContentDescription("Interactive 3D model. Drag to orbit, pinch to zoom, or use the viewport buttons.");w.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){if("https://forge.invalid/viewer.html".equals(request.getUrl().toString())&&"GET".equals(request.getMethod()))try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("viewer.html"));}catch(Exception ignored){}return new WebResourceResponse("text/plain","UTF-8",403,"Blocked",java.util.Collections.emptyMap(),new ByteArrayInputStream(new byte[0]));}@Override public void onPageFinished(WebView view,String url){if(view==viewer&&"https://forge.invalid/viewer.html".equals(url)){viewerReady=true;displayPending();}}@Override public boolean onRenderProcessGone(WebView view,android.webkit.RenderProcessGoneDetail detail){viewerReady=false;transferVersion++;ViewGroup parent=(ViewGroup)view.getParent();if(parent!=null)parent.removeView(view);view.destroy();if(viewer==view)viewer=null;showError("3D viewer stopped","Your files are safe. Restart Forge and try a lower LOD.");return true;}});w.loadUrl("https://forge.invalid/viewer.html");}
''')
change('    private void showGlbBytes(',r'''
    private void showGlbBytes(byte[] model,byte[] collision){if(isDestroyed())return;pendingModel=model;pendingCollision=collision;displayPending();}
''')
change('    private void transferToViewer(',r'''
    private void transferToViewer(String channel,String value,Runnable done){final int ticket=transferVersion;final WebView target=viewer;class Transfer implements Runnable{int offset;@Override public void run(){if(isDestroyed()||target!=viewer||viewer==null||!viewerReady||!started||currentScreen!=Screen.CREATE||ticket!=transferVersion)return;if(offset>=value.length()){done.run();return;}int end=Math.min(value.length(),offset+64*1024);String chunk=value.substring(offset,end);offset=end;target.evaluateJavascript("window.forgeTransferChunk('"+channel+"','"+chunk+"')",ignored->run());}}new Transfer().run();}
''')
change('    private void transferChunk(',r'''    private void unusedOldTransfer(){}''')
s=s.replace('    private void unusedOldTransfer(){}','')
s=s.replace('if(!viewerReady)return;String js;','if(!viewerReady||viewer==null)return;String js;').replace('switch(cmd){case "Solid":','switch(cmd){case "Left":js="window.forgeOrbit(-0.25)";break;case "Right":js="window.forgeOrbit(0.25)";break;case "Zoom +":js="window.forgeZoom(0.85)";break;case "Zoom -":js="window.forgeZoom(1.18)";break;case "Solid":')
change('    private void downloadSelected(',r'''
    private void downloadSelected(boolean share){if(selectedAsset==null&&!localUri.isEmpty()){Uri uri=Uri.parse(localUri);runAsync(()->DownloadsStore.write(getContentResolver(),"ForgeLocalAsset.glb","model/gltf-binary",readUriBounded(uri,GlbSafety.MAX_BYTES)),saved->exportFinished(saved,share),"Local export failed");return;}if(!ensureAsset())return;String directory=selectedAsset.optString("directory");int level=selectedLod;runAsync(()->{JSONObject result=client.rpc("asset.glb",new JsonObject().put("directory",directory).put("lod",level).put("collision",false));return DownloadsStore.write(getContentResolver(),result.optString("file","ForgeAsset.glb"),"model/gltf-binary",decodeModel(result));},saved->exportFinished(saved,share),"Asset export failed");}
''')
change('    private Uri saveToDownloads(',r'''    private Uri saveToDownloads(String name,byte[] bytes)throws Exception{return DownloadsStore.write(getContentResolver(),name,"model/gltf-binary",bytes).uri;}''')
s=s.replace('i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share Forge asset"))','i.setClipData(android.content.ClipData.newRawUri(name,uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share Forge asset"))')
change('    private void pairManual(',r'''    private void pairManual(){try{confirmPair(PairingInfo.parseManual(text(pairHost),text(pairPort),text(pairCode)));}catch(IllegalArgumentException error){showError("Invalid pairing details",error.getMessage());}}''')
change('    private void pairFromUri(',r'''    private void pairFromUri(String uri){try{confirmPair(PairingInfo.parseUri(uri));}catch(IllegalArgumentException error){showError("Invalid pairing link",error.getMessage());}}''')
change('    private void processIntent(',r'''    private void processIntent(Intent intent){if(intent==null)return;Uri uri=intent.getData();intent.setData(null);if(uri!=null&&"nexuforge".equalsIgnoreCase(uri.getScheme())){showScreen(Screen.PAIR);pairFromUri(uri.toString());}}''')
s=s.replace('(d,w)->{client.forget();renderPairState();}', '(d,w)->runAsync(()->{client.forget();return true;},done->{lastJobId=null;stopPolling();renderPairState();persistUi();},"Forget pairing failed")')
s=s.replace('"Windows Forge is reachable · "+r.optString("version","unknown version")','"Endpoint reachable. Pairing is still required to authenticate it."')
s=s.replace('styleInput(pairCode,"24-character pairing code",false);','styleInput(pairCode,"24-character pairing code",false);pairCode.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);pairCode.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);pairPort.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);')
change('    private void setCreateStatus(',r'''    private void setCreateStatus(String stage,int value){if(createStatus!=null&&!android.text.TextUtils.equals(createStatus.getText(),stage))createStatus.setText(stage);if(generationProgress!=null){generationProgress.setIndeterminate(value!=100&&(stage.contains("…")||stage.contains("Planning")||stage.contains("Interpreting")));generationProgress.setMax(100);generationProgress.setProgress(value==100?100:0);}}''')
change('    private void runRpc(',r'''
    private void runRpc(String method,JSONObject params,ResultHandler success,String title){if(!client.isPaired()){showScreen(Screen.PAIR);toast("Pair Windows Forge first.");return;}boolean write=method.equals("build")||method.endsWith(".apply");if(write&&writeBusy){toast("A request is still being sent. Check Queue before retrying.");return;}if(write)writeBusy=true;runAsync(()->{try{return client.rpc(method,params);}finally{if(write)writeBusy=false;}},success::handle,title);}
''')
change('    private <T> void runAsync(',r'''
    private <T> void runAsync(ThrowingSupplier<T> task,ResultHandlerT<T> success,String title){if(isDestroyed()||io.isShutdown())return;io.execute(()->{try{T result=task.get();ui.post(()->{if(isDestroyed()||isFinishing())return;try{success.handle(result);}catch(Exception error){Diagnostics.record(this,title,error);showError(title,message(error));}});}catch(Exception error){Diagnostics.record(this,title,error);ui.post(()->{if(isDestroyed()||isFinishing())return;setCreateStatus("Operation stopped. Your previous versions are safe.",0);showError(title,message(error));});}});}
''')
change('    private byte[] readUriBounded(',r'''
    private byte[] readUriBounded(Uri uri,int max)throws Exception{if(uri==null||!"content".equals(uri.getScheme()))throw new IllegalArgumentException("Use Android Documents to open the file.");try(java.io.InputStream in=getContentResolver().openInputStream(uri);java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream()){if(in==null)throw new IllegalArgumentException("File could not be opened.");byte[] block=new byte[16384];int total=0,n;while((n=in.read(block))!=-1){total+=n;if(total>max)throw new IllegalArgumentException("GLB exceeds the 32 MB mobile preview limit.");out.write(block,0,n);}byte[] bytes=out.toByteArray();GlbSafety.validate(bytes);return bytes;}}
''')
change('    private void restoreUi(',r'''
    private void restoreUi(Bundle saved){android.content.SharedPreferences prefs=getPreferences(MODE_PRIVATE);try{currentScreen=Screen.valueOf(saved==null?prefs.getString("screen","CREATE"):saved.getString("screen","CREATE"));}catch(Exception ignored){currentScreen=Screen.CREATE;}lastJobId=saved==null?prefs.getString("lastJob",null):saved.getString("lastJob",null);referenceUri=prefs.getString("referenceUri","");localUri=prefs.getString("localUri","");selectedLod=Math.max(0,Math.min(8,prefs.getInt("lod",0)));try{String a=prefs.getString("selectedAsset","");if(a!=null&&!a.isEmpty()&&a.length()<32768)selectedAsset=new JSONObject(a);}catch(Exception ignored){selectedAsset=null;}}
''')
change('    private void restorePromptOnly(',r'''
    private void restorePromptOnly(){android.content.SharedPreferences prefs=getPreferences(MODE_PRIVATE);prompt.setText(prefs.getString("prompt",""));refineText.setText(prefs.getString("refine",""));materialText.setText(prefs.getString("material",""));profile.setSelection(Math.max(0,Math.min(1,prefs.getInt("profile",0))));mode.setSelection(Math.max(0,Math.min(2,prefs.getInt("mode",0))));if(reference!=null)referenceSummary.setText(reference.fileName+" · restored local reference");}
''')
change('    private void persistUi(',r'''
    private void persistUi(){android.content.SharedPreferences.Editor edit=getPreferences(MODE_PRIVATE).edit().putString("screen",currentScreen.name()).putString("lastJob",lastJobId).putString("referenceUri",referenceUri).putString("localUri",localUri).putInt("lod",selectedLod);if(prompt!=null)edit.putString("prompt",text(prompt));if(refineText!=null)edit.putString("refine",text(refineText));if(materialText!=null)edit.putString("material",text(materialText));if(profile!=null)edit.putInt("profile",profile.getSelectedItemPosition());if(mode!=null)edit.putInt("mode",mode.getSelectedItemPosition());if(selectedAsset!=null&&selectedAsset.toString().length()<32768)edit.putString("selectedAsset",selectedAsset.toString());else edit.remove("selectedAsset");edit.apply();}
''')
s=s.replace('if(isFinishing())return;new AlertDialog','if(isFinishing()||isDestroyed()||!started)return;new AlertDialog').replace('setMessage(message==null?"Unknown error.":message)','setMessage(message==null?"Unknown error.":message.substring(0,Math.min(1200,message.length())))')
s=s.replace('e.setSingleLine(!multiline);e.setMinHeight(dp(52));','e.setSingleLine(!multiline);e.setContentDescription(hint);e.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(2000)});e.setMinHeight(dp(52));')
s=s.replace('t.setPadding(0,dp(8),0,dp(8));return t;','t.setPadding(0,dp(8),0,dp(8));t.setAccessibilityHeading(true);return t;')
helpers=r'''
    private void displayPending(){if(pendingModel==null||viewer==null||!viewerReady||!started||currentScreen!=Screen.CREATE)return;final byte[] model=pendingModel,collision=pendingCollision;final int ticket=++transferVersion;final WebView target=viewer;runAsync(()->new String[]{java.util.Base64.getEncoder().encodeToString(model),collision==null?null:java.util.Base64.getEncoder().encodeToString(collision)},encoded->{if(ticket!=transferVersion||viewer!=target||!started||currentScreen!=Screen.CREATE)return;target.evaluateJavascript("window.forgeTransferBegin()",ignored->{if(ticket!=transferVersion||viewer!=target)return;Runnable done=()->{if(ticket==transferVersion&&viewer==target){pendingModel=null;pendingCollision=null;target.evaluateJavascript("window.forgeTransferCommit().catch(e=>document.getElementById('state').textContent=e.message)",null);}};transferToViewer("model",encoded[0],()->{if(encoded[1]!=null)transferToViewer("collision",encoded[1],done);else done.run();});},"3D transfer failed");}
    private static byte[] decodeModel(JSONObject result)throws Exception{String encoded=result.optString("base64","");if(encoded.length()>45*1024*1024)throw new IllegalArgumentException("Model is too large for the mobile viewport.");byte[] data=java.util.Base64.getDecoder().decode(encoded);if(result.optLong("size",-1)!=data.length)throw new IllegalArgumentException("Model transfer size mismatch.");GlbSafety.validate(data);return data;}
    private void exportFinished(DownloadsStore.Saved saved,boolean share){if(share){Intent intent=new Intent(Intent.ACTION_SEND);intent.setType(saved.mime);intent.putExtra(Intent.EXTRA_STREAM,saved.uri);intent.setClipData(android.content.ClipData.newRawUri(saved.name,saved.uri));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,"Share Forge export"));}else new AlertDialog.Builder(this).setTitle("Verified export saved").setMessage("Downloads/Nexu AI 3D Forge/"+saved.name+"\n\nSHA-256\n"+saved.sha256).setPositiveButton("OK",null).setNeutralButton("Share",(d,w)->exportFinished(saved,true)).show();}
    private void confirmPair(PairingInfo info){new AlertDialog.Builder(this).setTitle("Trust this Windows Forge?").setMessage(info.host+":"+info.port+"\n\nConfirm this address and pairing offer belong to your PC on your private network. "+(client.isPaired()?"This replaces the current Android pairing. ":"")+"No model files are deleted.").setNegativeButton("Cancel",null).setPositiveButton("Pair",(d,w)->runAsync(()->client.pair(info,Build.MANUFACTURER+" "+Build.MODEL),r->{if(pairCode!=null)pairCode.setText("");renderPairState();toast("Paired with Windows Forge.");refreshAssets();loadPresets();},"Pairing failed")).show();}
    private void previewChange(String kind,JSONObject params){runRpc(kind+".plan",params,result->{JSONObject plan=result.optJSONObject("plan");if(plan==null){showError("No validated plan","Windows returned no changes to review.");return;}JSONArray changes=plan.optJSONArray("changes");String detail=changes==null?"A validated new asset version will be created.":JsonObject.pretty(new JsonObject().put("changes",changes));if(detail.length()>6000)detail=detail.substring(0,6000);new AlertDialog.Builder(this).setTitle("Review "+kind+" changes").setMessage(detail+"\n\nYour previous version is preserved.").setNegativeButton("Cancel",null).setPositiveButton("Apply new version",(d,w)->runRpc(kind+".apply",params,r->{JSONObject job=r.optJSONObject("job");if(job!=null)watchJob(job.optString("id"));},"Change could not start")).show();},"Change preview failed");}
    private void loadPresets(){if(!client.isPaired()||materialPreset==null)return;runRpc("material.presets",new JsonObject(),r->{JSONArray array=r.optJSONArray("presets");if(array==null)return;presetIds.clear();presetIds.add("");List<String> names=new ArrayList<>();names.add("No preset — use description");for(int i=0;i<array.length();i++){JSONObject item=array.optJSONObject(i);if(item!=null){presetIds.add(item.optString("id"));names.add(item.optString("label",item.optString("id")));}}ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,names);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);materialPreset.setAdapter(adapter);},"Material presets unavailable");}
    private void updateMaterialSlots(){if(materialSlot==null)return;materialNames.clear();JSONArray array=selectedAsset.optJSONArray("materials");if(array!=null)for(int i=0;i<array.length();i++){JSONObject m=array.optJSONObject(i);if(m!=null&&!m.optString("name").isEmpty())materialNames.add(m.optString("name"));}List<String> names=new ArrayList<>(materialNames);if(names.isEmpty())names.add("First material slot");ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,names);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);materialSlot.setAdapter(adapter);}
    private void showCatalogue(){if(!ensurePaired())return;runRpc("grammar.catalogue",new JsonObject(),r->{JSONArray array=r.optJSONArray("grammars");StringBuilder text=new StringBuilder("Supported procedural asset families:\n\n");if(array!=null)for(int i=0;i<array.length();i++){JSONObject g=array.optJSONObject(i);if(g!=null)text.append(g.optString("label",g.optString("name",g.optString("id","Asset")))).append('\n');}text.append("\nAdd materials, style, dimensions, triangle target and LOD count. Interpret checks what Forge understood.");new AlertDialog.Builder(this).setTitle("Creation catalogue").setMessage(text.toString()).setPositiveButton("Close",null).show();},"Catalogue unavailable");}
    private void feedback(String verdict){if(!ensureAsset())return;String directory=selectedAsset.optString("directory");EditText note=new EditText(this);styleInput(note,"Optional feedback, stored on your Windows Forge",true);note.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(500)});new AlertDialog.Builder(this).setTitle(verdict.equals("good")?"Good result":"Needs work").setView(note).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->runRpc("learning.feedback",new JsonObject().put("directory",directory).put("verdict",verdict).put("note",text(note)),r->toast("Feedback saved on Windows Forge."),"Feedback failed")).show();}
    private void restoreDocuments(){if(referenceUri!=null&&referenceUri.startsWith("content://")){String uri=referenceUri;runAsync(()->{try{return ReferenceEvidence.read(getContentResolver(),Uri.parse(uri),"reference");}catch(Exception e){Diagnostics.record(this,"reference restore",e);return null;}},value->{reference=value;if(referenceSummary!=null)referenceSummary.setText(value==null?"Reference unavailable. Choose it again.":value.fileName+" · restored reference");if(value==null){referenceUri="";persistUi();}},"Reference restore failed");}if(selectedAsset==null&&localUri!=null&&localUri.startsWith("content://")){String uri=localUri;runAsync(()->readUriBounded(Uri.parse(uri),GlbSafety.MAX_BYTES),bytes->{if(createPage==null)createPage=buildCreatePage();showGlbBytes(bytes,null);if(selectedAssetLabel!=null)selectedAssetLabel.setText("Restored local GLB · not uploaded");},"Local model restore failed");}}
    private void exportDiagnostics(){runAsync(()->DownloadsStore.write(getContentResolver(),"Nexu-Forge-diagnostics.txt","text/plain",Diagnostics.report(this,client.isPaired()).getBytes(StandardCharsets.UTF_8)),saved->exportFinished(saved,true),"Diagnostic export failed");}
    private int controlHeight(int value){return dp(Math.round(value*Math.max(1f,getResources().getConfiguration().fontScale)));}
'''
s=s.replace('    private interface ResultHandler{',helpers+'\n    private interface ResultHandler{')
s=s.replace('scroll.addView(col);ui.post(this::renderPairState);return scroll;','Button report=button("Share diagnostic report");report.setOnClickListener(v->exportDiagnostics());col.addView(report,new LinearLayout.LayoutParams(-1,dp(54)));col.addView(caption("Diagnostics exclude pairing secrets, prompts, images and host addresses."));scroll.addView(col);ui.post(this::renderPairState);return scroll;')
for size in (48,50,52,54,56,58,64,70):s=s.replace('dp('+str(size)+')','controlHeight('+str(size)+')')
s=s.replace('setId(911)','setId(R.id.asset_list)').replace('findViewById(911)','findViewById(R.id.asset_list)').replace('setId(912)','setId(R.id.job_list)').replace('findViewById(912)','findViewById(R.id.job_list)')
p.write_text(s)
(root/'app/src/main/res/values/ids.xml').write_text('<resources><item type="id" name="asset_list"/><item type="id" name="job_list"/></resources>\n')
gradle=root/'app/build.gradle';g=gradle.read_text();g=g.replace("testImplementation 'junit:junit:4.13.2'","testImplementation 'junit:junit:4.13.2'\n    testImplementation 'org.json:json:20260719'")
if 'gradle.projectsEvaluated' in g:g=g[:g.index('gradle.projectsEvaluated')]
gradle.write_text(g)
viewer=root/'app/src/main/assets/viewer.html';v=viewer.read_text();v=v.replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data: blob:; connect-src \'none\'; object-src \'none\'; base-uri \'none\'">',1)
# Static viewport-only operations; the existing renderer remains locally bundled.
v=v.replace('</script>','window.forgeOrbit=(delta)=>{viewer.yaw+=delta;viewer.render();};window.forgeZoom=(factor)=>{viewer.distance*=factor;viewer.render();};</script>')
viewer.write_text(v)
Path('evidence/android-source-integrity.txt').write_text('Original source archive verified before ordinary source-level repairs.\nMainActivity SHA256: '+hashlib.sha256(p.read_bytes()).hexdigest()+'\nNo encoded activity data used in this build.\n')
print('Android-only source repairs applied; desktop input unchanged.')
