/**
 * Minted Up — domain types.
 *
 * Everything in the marketplace is scoped to antiques and collectibles. The
 * taxonomy in `categories.ts` is the only vocabulary listings may use.
 */

export type Role = "user" | "admin";

export type User = {
  id: string;
  email: string;
  handle: string;
  displayName: string;
  role: Role;
  passwordHash: string;
  passwordSalt: string;
  shop: Shop;
  createdAt: string;
  suspended: boolean;
};

export type Shop = {
  name: string;
  slug: string;
  tagline: string;
  about: string;
  location: string;
  /** Specialisms, drawn from the category taxonomy. Powers shop-level SEO. */
  specialties: string[];
  returnsPolicy: string;
  shippingPolicy: string;
};

export type ListingFormat = "buy" | "bid";

export type ListingStatus = "draft" | "active" | "sold" | "ended" | "removed";

/** Result of the high-end image gate. Stored so admin can audit decisions. */
export type ImageQuality = {
  width: number;
  height: number;
  megapixels: number;
  bytes: number;
  format: "jpeg" | "png" | "webp";
  /** Bytes of file per pixel — low values betray an upscaled or re-compressed file. */
  bytesPerPixel: number;
  /** 0-100. Client-measured Laplacian variance, normalised. Absent for API uploads. */
  sharpness: number | null;
  score: number;
  accepted: boolean;
  failures: string[];
  warnings: string[];
};

export type ListingImage = {
  id: string;
  /** Slot index 0-29 on the composer grid. */
  slot: number;
  filename: string;
  mediaType: string;
  quality: ImageQuality;
  alt: string;
  uploadedAt: string;
};

export type Bid = {
  id: string;
  listingId: string;
  bidderId: string;
  amount: number;
  placedAt: string;
  /** Highest the bidder is willing to go; the engine bids up to this on their behalf. */
  maxAmount: number;
  retracted: boolean;
};

export type Order = {
  id: string;
  listingId: string;
  buyerId: string;
  sellerId: string;
  amount: number;
  format: ListingFormat;
  placedAt: string;
  status: "paid" | "shipped" | "delivered" | "refunded";
};

export type ListingAttributes = {
  maker: string;
  period: string;
  origin: string;
  materials: string[];
  marks: string;
  condition: string;
  conditionGrade: ConditionGrade;
  provenance: string;
  dimensions: string;
  signed: boolean;
  restored: boolean;
};

export type ConditionGrade =
  | "mint"
  | "excellent"
  | "very-good"
  | "good"
  | "fair"
  | "restoration-project";

export type Listing = {
  id: string;
  sellerId: string;
  title: string;
  subtitle: string;
  description: string;
  categoryId: string;
  format: ListingFormat;
  status: ListingStatus;
  /** Buy-it-now price, in minor units (pence/cents). */
  price: number;
  /** Auction opening bid, in minor units. */
  startingBid: number;
  reserve: number;
  currency: "GBP" | "USD" | "EUR";
  /** ISO date; auctions only. */
  endsAt: string | null;
  images: ListingImage[];
  attributes: ListingAttributes;
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
    /** Which fields were generated by the AI SEO assistant, for disclosure. */
    aiAssistedFields: string[];
  };
  /** Set when the beta auto-complete drafted this listing from its images. */
  autofilledFrom: string | null;
  researchSessionId: string | null;
  shipping: { domestic: number; international: number; collectionOnly: boolean };
  views: number;
  watchers: string[];
  createdAt: string;
  updatedAt: string;
  soldAt: string | null;
  soldPrice: number | null;
};

/* ------------------------------------------------------------------ *
 * Research gateway
 * ------------------------------------------------------------------ */

export type SignalType =
  | "mark"
  | "maker"
  | "material"
  | "form"
  | "motif"
  | "period"
  | "origin"
  | "condition"
  | "dimension"
  | "keyword";

/**
 * One observation about an object. `source` and `confidence` decide how much
 * weight the learning engine gives it — see `research.ts`.
 */
export type ResearchSignal = {
  id: string;
  type: SignalType;
  value: string;
  source: "user" | "ai" | "confirmed" | "rejected";
  confidence: number;
  notedAt: string;
};

export type ResearchSession = {
  id: string;
  userId: string;
  title: string;
  categoryId: string | null;
  notes: string;
  signals: ResearchSignal[];
  queries: string[];
  /** Set once the seller turns the research into a listing. */
  listingId: string | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * A document in the searchable research corpus. Documents come from three
 * places, and `tier` decides which wins when they disagree.
 */
export type ResearchDoc = {
  id: string;
  /** reference = curated/editorial, market = a real sale, community = user research. */
  tier: "reference" | "market" | "community";
  title: string;
  body: string;
  categoryId: string;
  terms: string[];
  /** Realised sale price in minor units, when this doc records an outcome. */
  realisedPrice: number | null;
  currency: "GBP" | "USD" | "EUR" | null;
  sourceListingId: string | null;
  contributedBy: string | null;
  /** Aggregate of the feedback events pointing at this doc. */
  weight: number;
  createdAt: string;
};

/**
 * Append-only log. Every interaction in the research gateway lands here, and
 * the index is rebuilt from it. Nothing else is allowed to mutate learned
 * state, so the whole model is reproducible from this one table.
 */
export type LearningEvent = {
  id: string;
  sessionId: string | null;
  userId: string | null;
  kind:
    | "query"
    | "suggestion_shown"
    | "suggestion_accepted"
    | "suggestion_rejected"
    | "signal_added"
    | "listing_published"
    | "sale_outcome"
    | "no_sale_outcome";
  terms: string[];
  categoryId: string | null;
  docId: string | null;
  /** Realised price in minor units for outcome events. */
  value: number | null;
  weight: number;
  createdAt: string;
};

export type Session = {
  token: string;
  userId: string;
  createdAt: string;
  expiresAt: string;
};

export type Database = {
  users: User[];
  listings: Listing[];
  bids: Bid[];
  orders: Order[];
  sessions: Session[];
  researchSessions: ResearchSession[];
  researchDocs: ResearchDoc[];
  learningEvents: LearningEvent[];
};
